# Generated by Django 5.2.1 on 2025-06-15 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_comment_course_alter_comment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='enable_chat',
            field=models.BooleanField(default=True, verbose_name='تمكين الدردشة'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_recording',
            field=models.BooleanField(default=False, verbose_name='تمكين التسجيل'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_screen_share',
            field=models.BooleanField(default=True, verbose_name='تمكين مشاركة الشاشة'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_live_started',
            field=models.BooleanField(default=False, verbose_name='بدأ الاجتماع المباشر'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='live_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الاجتماع المباشر'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الاجتماع المباشر'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.IntegerField(default=50, verbose_name='الحد الأقصى للمشاركين'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_room_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف غرفة الاجتماع'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('ZOOM', 'اجتماع عبر زووم'), ('NORMAL', 'اجتماع عادي'), ('LIVE', 'اجتماع مباشر')], max_length=10, verbose_name='نوع الاجتماع'),
        ),
        migrations.CreateModel(
            name='MeetingChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='رسالة نظام')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='website.meeting', verbose_name='الاجتماع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة دردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'ordering': ['timestamp'],
            },
        ),
    ]
