# Generated by Django 5.2.1 on 2025-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_articlecategory_bookcategory_school_article_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('published', 'منشور'), ('draft', 'مسودة')], default='pending', max_length=20),
        ),
    ]
