# Generated by Django 5.2.1 on 2025-06-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_meeting_enable_chat_meeting_enable_recording_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('template_style', models.CharField(choices=[('modern', 'تصميم حديث'), ('classic', 'تصميم كلاسيكي'), ('elegant', 'تصميم أنيق'), ('professional', 'تصميم مهني')], default='modern', max_length=20, verbose_name='نمط الشهادة')),
                ('primary_color', models.CharField(choices=[('#2a5a7c', 'أزرق'), ('#28a745', 'أخضر'), ('#dc3545', 'أحمر'), ('#ffc107', 'أصفر'), ('#6f42c1', 'بنفسجي'), ('#fd7e14', 'برتقالي')], default='#2a5a7c', max_length=7, verbose_name='اللون الأساسي')),
                ('institution_name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='certificate_templates/logos/', verbose_name='شعار المؤسسة')),
                ('signature_name', models.CharField(max_length=255, verbose_name='اسم الموقع')),
                ('signature_title', models.CharField(max_length=255, verbose_name='منصب الموقع')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/signatures/', verbose_name='صورة التوقيع')),
                ('certificate_text', models.TextField(default='هذا يشهد بأن {student_name} قد أكمل بنجاح دورة {course_name} بتاريخ {completion_date}', help_text='يمكنك استخدام المتغيرات: {student_name}, {course_name}, {completion_date}, {institution_name}', verbose_name='نص الشهادة')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='إضافة رمز QR للتحقق')),
                ('include_grade', models.BooleanField(default=False, verbose_name='إضافة الدرجة في الشهادة')),
                ('is_default', models.BooleanField(default=False, verbose_name='القالب الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منشئ القالب')),
            ],
            options={
                'verbose_name': 'قالب الشهادة',
                'verbose_name_plural': 'قوالب الشهادات',
                'ordering': ['-created_at'],
            },
        ),
    ]
