# Generated by Django 5.2.1 on 2025-06-16 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_certificatetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب الجاهز')),
                ('description', models.TextField(verbose_name='وصف القالب')),
                ('template_style', models.CharField(choices=[('modern', 'تصميم حديث'), ('classic', 'تصميم كلاسيكي'), ('elegant', 'تصميم أنيق'), ('professional', 'تصميم مهني'), ('creative', 'تصميم إبداعي'), ('minimalist', 'تصميم بسيط'), ('colorful', 'تصميم ملون'), ('corporate', 'تصميم شركات')], max_length=20, verbose_name='نمط القالب')),
                ('primary_color', models.CharField(default='#2a5a7c', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#28a745', max_length=7, verbose_name='اللون الثانوي')),
                ('background_pattern', models.CharField(default='none', max_length=50, verbose_name='نمط الخلفية')),
                ('border_style', models.CharField(default='classic', max_length=50, verbose_name='نمط الحدود')),
                ('font_family', models.CharField(default='Arial', max_length=100, verbose_name='نوع الخط')),
                ('preview_image', models.ImageField(upload_to='preset_templates/', verbose_name='صورة المعاينة')),
                ('template_html', models.TextField(verbose_name='كود HTML للقالب')),
                ('template_css', models.TextField(verbose_name='كود CSS للقالب')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='التصنيف')),
                ('is_featured', models.BooleanField(default=False, verbose_name='قالب مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب جاهز',
                'verbose_name_plural': 'القوالب الجاهزة',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_pattern',
            field=models.CharField(default='none', max_length=50, verbose_name='نمط الخلفية'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='border_style',
            field=models.CharField(default='classic', max_length=50, verbose_name='نمط الحدود'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='font_family',
            field=models.CharField(default='Arial', max_length=100, verbose_name='نوع الخط'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_completion_date',
            field=models.BooleanField(default=True, verbose_name='إضافة تاريخ الإكمال'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_course_duration',
            field=models.BooleanField(default=False, verbose_name='إضافة مدة الدورة'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='قالب عام (يمكن للجميع استخدامه)'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات المعاينة'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='secondary_color',
            field=models.CharField(choices=[('#2a5a7c', 'أزرق'), ('#28a745', 'أخضر'), ('#dc3545', 'أحمر'), ('#ffc107', 'أصفر'), ('#6f42c1', 'بنفسجي'), ('#fd7e14', 'برتقالي'), ('#17a2b8', 'سماوي'), ('#e83e8c', 'وردي'), ('#6c757d', 'رمادي'), ('#343a40', 'أسود')], default='#28a745', max_length=7, verbose_name='اللون الثانوي'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_source',
            field=models.CharField(choices=[('custom', 'قالب مخصص'), ('preset', 'قالب جاهز'), ('imported', 'قالب مستورد')], default='custom', max_length=20, verbose_name='مصدر القالب'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/user_signatures/', verbose_name='توقيع المستخدم'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='primary_color',
            field=models.CharField(choices=[('#2a5a7c', 'أزرق'), ('#28a745', 'أخضر'), ('#dc3545', 'أحمر'), ('#ffc107', 'أصفر'), ('#6f42c1', 'بنفسجي'), ('#fd7e14', 'برتقالي'), ('#17a2b8', 'سماوي'), ('#e83e8c', 'وردي'), ('#6c757d', 'رمادي'), ('#343a40', 'أسود')], default='#2a5a7c', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_style',
            field=models.CharField(choices=[('modern', 'تصميم حديث'), ('classic', 'تصميم كلاسيكي'), ('elegant', 'تصميم أنيق'), ('professional', 'تصميم مهني'), ('creative', 'تصميم إبداعي'), ('minimalist', 'تصميم بسيط'), ('colorful', 'تصميم ملون'), ('corporate', 'تصميم شركات')], default='modern', max_length=20, verbose_name='نمط الشهادة'),
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التوقيع')),
                ('signature_image', models.ImageField(upload_to='user_signatures/', verbose_name='صورة التوقيع')),
                ('is_default', models.BooleanField(default=False, verbose_name='التوقيع الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توقيع المستخدم',
                'verbose_name_plural': 'توقيعات المستخدمين',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
