# Generated by Django 5.2.1 on 2025-06-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_presetcertificatetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersignature',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'توقيع المستخدم', 'verbose_name_plural': 'توقيعات المستخدمين'},
        ),
        migrations.RenameField(
            model_name='usersignature',
            old_name='name',
            new_name='signature_name',
        ),
        migrations.AlterUniqueTogether(
            name='usersignature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersignature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='usersignature',
            name='signature_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='usersignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True, verbose_name='رقم الشهادة')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('completion_date', models.DateTimeField(verbose_name='تاريخ إكمال الدورة')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('course_title', models.CharField(max_length=500, verbose_name='عنوان الدورة')),
                ('institution_name', models.CharField(default='أكاديمية التعلم الإلكتروني', max_length=255, verbose_name='اسم المؤسسة')),
                ('final_grade', models.FloatField(blank=True, null=True, verbose_name='الدرجة النهائية')),
                ('completion_percentage', models.FloatField(default=100.0, verbose_name='نسبة الإكمال')),
                ('course_duration_hours', models.IntegerField(blank=True, null=True, verbose_name='مدة الدورة بالساعات')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('revoked', 'ملغية'), ('expired', 'منتهية الصلاحية')], default='active', max_length=20, verbose_name='حالة الشهادة')),
                ('verification_status', models.CharField(choices=[('verified', 'تم التحقق'), ('pending', 'في انتظار التحقق'), ('failed', 'فشل التحقق')], default='verified', max_length=20, verbose_name='حالة التحقق')),
                ('verification_code', models.CharField(max_length=50, unique=True, verbose_name='رمز التحقق')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/', verbose_name='ملف PDF')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/', verbose_name='صورة رمز QR')),
                ('digital_signature', models.TextField(blank=True, null=True, verbose_name='التوقيع الرقمي')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='تم التحقق من التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='website.course', verbose_name='الدورة')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='أصدرت بواسطة')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.certificatetemplate', verbose_name='قالب الشهادة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-date_issued'],
                'indexes': [models.Index(fields=['certificate_id'], name='website_cer_certifi_e0a78c_idx'), models.Index(fields=['verification_code'], name='website_cer_verific_905964_idx'), models.Index(fields=['user', 'status'], name='website_cer_user_id_679e76_idx'), models.Index(fields=['course', 'status'], name='website_cer_course__2141dd_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
