# Generated by Django 5.2.1 on 2025-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='materials_pdf',
            field=models.FileField(blank=True, help_text='Upload additional course materials PDF', null=True, upload_to='course_pdfs/materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_pdf',
            field=models.FileField(blank=True, help_text='Upload course syllabus PDF', null=True, upload_to='course_pdfs/syllabus/'),
        ),
    ]
