# Generated by Django 5.2.1 on 2025-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_article_category_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_pdf',
            field=models.FileField(blank=True, help_text='Upload module PDF material', null=True, upload_to='module_pdfs/'),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_description',
            field=models.CharField(blank=True, help_text='وصف ملف PDF', max_length=500, null=True),
        ),
    ]
