# Generated by Django 5.2.1 on 2025-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_module_module_pdf_module_pdf_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pdf_description',
        ),
        migrations.AddField(
            model_name='module',
            name='additional_materials',
            field=models.FileField(blank=True, help_text='Upload additional materials', null=True, upload_to='module_materials/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_pdf',
            field=models.FileField(blank=True, help_text='Upload module PDF materials', null=True, upload_to='module_pdfs/'),
        ),
    ]
