# Generated by Django 5.2.1 on 2025-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_module_pdf_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF or other document files', null=True, upload_to='notes_files/'),
        ),
    ]
