# Generated by Django 5.2.1 on 2025-05-31 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_notes_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('note', 'Note/PDF'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course'], name='website_con_user_id_2902d1_idx'), models.Index(fields=['content_type', 'content_id'], name='website_con_content_be3f91_idx')],
                'unique_together': {('user', 'course', 'content_type', 'content_id')},
            },
        ),
    ]
