# Generated by Django 5.2.1 on 2025-06-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('website', '0016_contentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='نبذة عنك')),
                ('specialization', models.CharField(max_length=255, verbose_name='التخصص')),
                ('cv', models.FileField(blank=True, null=True, upload_to='teacher_applications/cvs/', verbose_name='السيرة الذاتية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to='user.profile')),
            ],
            options={
                'verbose_name': 'طلب انضمام معلم',
                'verbose_name_plural': 'طلبات الانضمام كمعلمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
