# Generated by Django 5.2.1 on 2025-06-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_teacherapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherApplication',
        ),
    ]
