# Generated by Django 5.2.1 on 2025-06-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_add_meeting_updated_at'),
    ]

    operations = [
    ]
