# Generated by Django 5.2.2 on 2025-06-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_teacherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Organization', 'Organization')], default='Student', max_length=2000, null=True),
        ),
    ]
